# Generated by Django 3.1.4 on 2020-12-13 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twwiki_twitter_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki_tweet',
            name='author',
            field=models.ForeignKey(default='sebi', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wiki_tweet',
            name='title',
            field=models.CharField(default='sebi', max_length=200),
            preserve_default=False,
        ),
    ]
