# Generated by Django 3.1.4 on 2020-12-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twwiki_twitter_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki_tweet',
            name='date',
        ),
        migrations.AddField(
            model_name='wiki_tweet',
            name='mainMedia',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='wiki_tweet',
            name='originalHTML',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wiki_tweet',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
