# Generated by Django 3.1.4 on 2020-12-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twwiki_twitter_bot', '0002_auto_20201226_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki_tweet',
            name='mainMedia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
