# Generated by Django 3.1.4 on 2020-12-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twwiki_twitter_bot', '0003_auto_20201226_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki_tweet',
            name='isDateTweet',
            field=models.BooleanField(default=False),
        ),
    ]
