# Generated by Django 3.1.4 on 2020-12-30 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twwiki_twitter_bot', '0004_wiki_tweet_isdatetweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki_tweet',
            name='isDateTweet',
        ),
    ]
