# Generated by Django 3.1.4 on 2020-12-30 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twwiki_twitter_bot', '0006_auto_20201229_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki_tweet',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
