# Generated by Django 3.1.4 on 2021-01-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twwiki_twitter_bot', '0007_auto_20201229_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki_tweet',
            name='isDateTweetField',
            field=models.BooleanField(default=False),
        ),
    ]
